project/blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.conf.urls import include
from django.urls import path
# from posts import views
from accounts.views import (login_view, register_view, logout_view)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('comments/', include('comments.urls', namespace='comments')),
    path('login/', login_view, name='login'),
    path('register/', register_view, name='register'),
    path('logout/', logout_view, name='logout'),
    path('', include('posts.urls', namespace='posts')),
    path('api/comments/', include('comments.api.urls', namespace='comments-api')),
    path('api/posts/', include('posts.api.urls', namespace='posts-api')),
    path('api/users/', include('accounts.api.urls', namespace='users-api')),
     
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/posts/api/urls.py
from django.urls import path

from django.conf.urls import  url
from .views import (
	PostCreateAPIVeiw,
	PostDetailAPIVeiw,
	PostListAPIVeiw,
	PostUpdateAPIVeiw,
	PostDeleteAPIVeiw
	# post_list,
	# post_create,
	# post_detail,
	# post_update,
	# post_delete,
	)

app_name = 'posts'
urlpatterns = [

  path('',  PostListAPIVeiw.as_view(), name='list'),
  path('create/', PostCreateAPIVeiw.as_view(), name='create'),
  path('<slug:slug>/',PostDetailAPIVeiw.as_view(), name='detail'),
  path('<slug:slug>/edit/', PostUpdateAPIVeiw.as_view(), name='update'),
  path('<slug:slug>/delete/', PostDeleteAPIVeiw.as_view(), name='delete'),
]

project/posts/urls.py
from django.urls import path

from django.conf.urls import  url
from .views import (
	post_list,
	post_create,
	post_detail,
	post_update,
	post_delete,
	)

app_name = 'posts'
urlpatterns = [

  path('',  post_list, name='list'),
  path('create/', post_create),
  path('<slug:slug>/',post_detail, name='detail'),
  path('<slug:slug>/edit/', post_update, name='update'),
  path('<slug:slug>/delete/', post_delete),
]

project/posts/models.py
from django.urls import reverse
# from django.core.urlresolvers import reverse
from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.utils import timezone
from markdown_deux import markdown
from django.utils.safestring import mark_safe
from comments.models import Comment
from .utils import get_red_time
# Post.object.all()
class PostManager(models.Manager):
	def all(self, *args, **kwargs):
		return super(PostManager, self).filter(draft=False).filter(publish_lte=timezone.now())

# Create your models here.
def upload_location(instance, filename):
	return "%s/%s" %(instance.id, filename)


class Post(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=1)
	# user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1	)
	title = models.CharField(max_length=120)
	slug = models.SlugField(unique=True)
	image = models.ImageField(upload_to=upload_location, 
					null=True, 
					blank=True,
					width_field="width_field",
					height_field="height_field")
	height_field = models.IntegerField(default=0)
	width_field  = models.IntegerField(default=0)
	content = models.TextField()
	draft = models.BooleanField(default=0)
	publish = models.DateField(auto_now=False, auto_now_add=False)
	read_time = models.TimeField(null=True, blank=True)
	updated = models.DateTimeField(auto_now=True, auto_now_add=False)
	timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
	
	# objects = PostManager()

	def __unicode__(self):
		return self.title

	def __str__(self):
		return self.title

	def get_obsolute_url(self):
		return reverse("posts:detail", kwargs={"slug": self.slug})
		# return "/posts/%s" %(self.id)

	def get_api_url(self):
		return reverse("posts-api:detail", kwargs={"slug": self.slug})

	# create markdown function to pass it to posts list 
	def get_markdown(self):
		content = self.content
		mark_downtext = markdown(content)
		return mark_safe(mark_downtext)

	@property
	def comments(self):
		instance = self
		qs = Comment.objects.filter_by_instance(instance)
		return qs

	@property
	def get_content_type(self):
		instance = self
		content_type = ContentType.objects.get_for_model(instance.__class__)
		return content_type

	class Meta:
		ordering = ["-timestamp", "-updated"]

def create_slug(instance, new_slug=None):
	slug = slugify(instance.title)
	if new_slug is not None:
		slug = new_slug
	qs = Post.objects.filter(slug=slug).order_by("-id")
	exists = qs.exists()
	if exists:
		new_slug = "%s-%s" %(slug, qs.first().id)
		return create_slug(instance, new_slug=new_slug)
	return slug

# appeding the ID of the instance
def pre_save_post_reciever(sender, instance, *args, **kwargs):
	if not instance.slug:
		instance.slug = create_slug(instance)

	if instance.content:
		html_string = instance.get_markdown()
		read_time_var = get_red_time(html_string)
		instance.read_time = read_time_var

pre_save.connect(pre_save_post_reciever, sender=Post)

project/posts/forms.py
from django import forms

from .models import Post
from pagedown.widgets import PagedownWidget

class PostForms(forms.ModelForm):
	content = forms.CharField(widget=PagedownWidget(show_preview=False))
	publish = forms.DateField(label = '', widget=forms.SelectDateWidget)

	class Meta:
		model = Post
		fields = [
			"title",
			"content",
			"image",
			"draft",
			"publish",

		]

project/posts/api/views.py
from django.db.models import Q

# This in bult functions for search
from rest_framework.filters import (
	SearchFilter,
	OrderingFilter,
	)
# importing paginations
from .pagination import PostLimitOffsetPagination

from rest_framework.generics import (
	DestroyAPIView,
	ListAPIView,
	UpdateAPIView,
	RetrieveAPIView,
	CreateAPIView,
	RetrieveUpdateAPIView
	)

# To import user Permissions in Django apis
from rest_framework.permissions import(
	AllowAny,
	IsAuthenticated,
	IsAdminUser,
	IsAuthenticatedOrReadOnly,
	)

from .permissions import IsOwnerOrReadOnly

from posts.models import Post
from .serializers import (
	PostDetailSerializer,
	PostListSerializer,
	PostCreateUpdateSerializer,
	)


class PostCreateAPIVeiw(CreateAPIView):
	"""
	Create Content
	"""
	queryset = Post.objects.all()
	serializer_class = PostCreateUpdateSerializer
	# permissions_classes = [IsAuthenticated]

	# It changes to the user who create content to new user.
	def perform_create(self, serializer):
		serializer.save(user=self.request.user)



class PostDetailAPIVeiw(RetrieveAPIView):
	"""
	Retrieve a specific Content by ID
	"""
	queryset = Post.objects.all()
	serializer_class = PostDetailSerializer
	lookup_field = 'slug'
	permissions_classes = [AllowAny]

class PostUpdateAPIVeiw(RetrieveUpdateAPIView):
	"""
	Update Content By a slug or ID
	"""
	queryset = Post.objects.all()
	serializer_class = PostCreateUpdateSerializer
	lookup_field = 'slug'
	permissions_classes = [IsOwnerOrReadOnly]

	# create user Permissions
	def perform_update(self, serializer):
		serializer.save(user=self.request.user)


class PostDeleteAPIVeiw(DestroyAPIView):
	"""
	Delete Content By a slug or ID
	"""
	queryset = Post.objects.all()
	serializer_class = PostDetailSerializer
	lookup_field = 'slug'
	permissions_classes = [IsOwnerOrReadOnly]


class PostListAPIVeiw(ListAPIView):
	"""
	Retrivew all the Content
	"""
	serializer_class = PostListSerializer
	permissions_classes = [AllowAny]

	# You pass things to search
	filter_backends = [SearchFilter, OrderingFilter]
	search_fields = ['title', 'content', 'user_first_name']
	# Pagination
	pagination_class = PostLimitOffsetPagination


	def get_queryset(self, *args, **kwargs):
		# querset_list = super(PostListAPIVeiw, self).get_queryset(*args, **kwargs)
		querySet_list = Post.objects.all()
		query = self.request.GET.get("q")
		if query:
			querySet_list = querySet_list.filter(
								Q(title__icontains=query)|
								Q(content__icontains=query)|
								Q(user__username__icontains=query)
								).distinct()
		return querySet_list

project/posts/views.py
# from urllib import quote_plus
from urllib.parse import quote_plus  
from django.core.paginator import Paginator
from django.contrib import messages
from django.contrib.contenttypes.models import ContentType
# from django.contrib.contenttypes.models import ContentType
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect, Http404
from django.contrib.auth import authenticate
from django.utils import timezone
from django.db.models import Q
from comments.forms import CommentForm
from comments.models import Comment 
# Create your views here.
from .models import Post
from .forms import PostForms
# from .utils import get_red_time



def post_create(request):
	"""
	Methods creates the Posts
	"""
	if not request.user.is_staff or not request.user.is_superuser:
		raise Http404
		
	form = PostForms(request.POST or None, request.FILES or None)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.user = request.user
		instance.save()
		# message success
		messages.success(request, "Successfully Created")
		return HttpResponseRedirect(instance.get_obsolute_url())
	context = {
		"form": form,
	}
	return render(request, "post_form.html", context)


def post_detail(request, slug=None):
	instance = get_object_or_404(Post, slug=slug)
	# if instance.publish > timezone.now().date() or instance.draft:
		# if not request.user.is_staff or not request.user.is_superuser:
			# raise Http404
	share_string = quote_plus(instance.content)

	# counting words 
	# print(get_red_time(instance.get_markdown()))

	comments = instance.comments
	initial_data = {
			"content_type": instance.get_content_type,
			"object_id": instance.id
	}

	form  = CommentForm(request.POST or None, initial = initial_data)
	if form.is_valid(): #	and request.user.is_authenticated():
		
		c_type = form.cleaned_data.get("content_type")
		content_type = ContentType.objects.get(model=c_type)
		obj_id = form.cleaned_data.get('object_id')
		content_data  = form.cleaned_data.get("content")
		parent_obj = None
		try:
			parent_id = int(request.POST.get("parent_id"))# added on reply
		except:
			parent_id = None

		if parent_id:
			parent_qs = Comment.objects.filter(id=parent_id)
			if parent_qs.exists() and parent_qs.count() == 1:
				parent_obj = parent_qs.first()
	 
		new_comment, created = Comment.objects.get_or_create(
						user = request.user,
						content_type = content_type,
						object_id = obj_id,
						content = content_data,
						parent  = parent_obj,
					)
		return HttpResponseRedirect(new_comment.content_object.get_obsolute_url())

	context = {
		"title": instance.title,
		"instance": instance,
		"share_string": share_string,
		"comments": comments,
		"comment_form": form,
	}
	return render(request, "post_detail.html", context)


def post_list(request):
	""" list items """
	today = timezone.now().date()
	querySet_list = Post.objects.all()

	if request.user.is_staff or request.user.is_superuser:
		querySet_list = Post.objects.all()

	# Search posts
	query = request.GET.get("q")
	if query:
		querySet_list = querySet_list.filter(
							Q(title__icontains=query)|
							Q(content__icontains=query)|
							Q(user__username__icontains=query)
							).distinct()

	paginator = Paginator(querySet_list, 3)
	page = request.GET.get('page')
	querySet = paginator.get_page(page)

	context = {
		"query_list": querySet,
		"title":"list",
		"today": today
	}
	return render(request, "post_list.html", context)
	

def post_update(request, slug=None):
	"""
	It updates posts
	"""
	if not request.user.is_staff or not request.user.is_superuser:
		raise Http404
	instance = get_object_or_404(Post, slug=slug)
	form = PostForms(request.POST or None, request.FILES or None, instance = instance)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.save()
		# message success
		messages.success(request, "Successfuly updated")
		return HttpResponseRedirect(instance.get_obsolute_url())
	else:
		messages.error(request, "Not update")
	context = {
	"title": instance.title,
	"instance": instance,
	"form": form,
	}
	return render(request, "post_form.html", context)


def post_delete(request, slug=None):
	"""
	 delete Details 
	"""
	if not request.user.is_staff or not request.user.is_superuser:
		raise Http404
	instance = get_object_or_404(Post, slug=slug)
	instance.delete()
	messages.success(request, "Successfuly Deleted")
	return redirect("posts:list")

project/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title>{% block head_title %} Advancing Django {% endblock head_title %}</title>
	<link rel="stylesheet" href='{% static "css/base.css" %}' />
	<!-- Font Awesome -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
<!-- Bootstrap core CSS -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
<!-- Material Design Bootstrap -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.7.6/css/mdb.min.css" rel="stylesheet">
<script
			  src="https://code.jquery.com/jquery-2.2.4.min.js"
			  integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="
			  crossorigin="anonymous"></script>
	<style> 
	{% block style %} {% endblock style %}
	</style>


{% block head_extra %} {% endblock head_extra %}
</head>
<body>

<div id="fb-root"></div>
<script type="text/javascript">
	$(document).ready(function(){
		$(".content-markdown").each(function(){
			var content = $(this).text()
			var markedContent = marked(content)
			$(this).html(markedContent)
		})

		$(".post-detail-item img").each(function(){
				$(this).addClass("img-responsive")
		})
		// preview title
		var titleItem = $("#id_title");
		$("#preview-title").text(titleItem.val())

		var contentInput = $("#id_content");
		
		function setContent(value){
			var markedContent = marked(value)
			$("#preview-content").html(markedContent)
			$("#preview-content img").each(function(){
				$(this).addClass("img-responsive")
			})
		}
		setContent(contentInput.val())
		contentInput.keyup(function(){
			var newContent = $(this).val()
			setContent(newContent)
		})

		$(".comment-reply-btn").click(function(event){
			event.preventDefault();
			$(this).parent().next(".comment-reply").fadeToggle();

		})

	})

</script>
<script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.2&appId=1994101844153657&autoLogAppEvents=1"></script>

{% include "messages_display.html" %}

<html lang="en" class="full-height">

<!--Main Navigation-->
<header>

  <nav class="navbar fixed-top navbar-expand-lg navbar-dark indigo">
    <a class="navbar-brand" href="#"><strong>Navbar</strong></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href='{% url "posts:list" %}'>Home<span class="sr-only">(current)</span></a>
         {% block post_detail_link %}
		
					{% endblock %}

				{% if not request.user.is_authenticated %}
        </li>
        <li class="nav-item">
          <a class="nav-link" href='{% url "register" %}'>Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href='{% url "login" %}'>Login</a>
        </li>
        	{% else %}

         <li class="nav-item">
          <a class="nav-link" href='{% url "logout" %}'>Logout</a>

        </li>
                {% endif %}

      </ul>
    </div>
  </nav>



</header>
<!--Main Navigation-->

<!--Main Layout-->
<main class="text-center py-5">

 
  </div>

</main>
<!--Main Layout-->




<div class="container">

{% block content %}{% endblock content %}


</div>

<!-- JQuery -->

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.7.6/js/mdb.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.6.2/marked.min.js"></script>


</body>
</html>

project/templates/comment_thread.html
{% extends "base.html" %}

{% load urlify %}
{% load crispy_forms_tags %}

{% block head_title %} {{ instance.title }} | {{ block.supper }} {% endblock head_title %}
{% block content %}

{{ object }}

<div class="row">
<div class="col-sm-8 col-sm-offset-4">

			<p>{{ comment.content }}</p>

			<footer>Via {{ comment.user }} | {{ comment.timestamp|timesince }} ago | {% if comment.children.count > 0 %} {{ comment.children.count }} Comment{% if comment.children.count > 1 %}s {% endif %}| {% endif %}{% if request.user == comment.user %} <a href="{{ comment.get_delete_url }}">Delete</a> {% endif %}</footer>
			<hr/>
			<!-- Replies -->
	<div>
			{% for child_comment in comment.children %}
			<blockquote>

			<p>{{ child_comment.content }}</p>

			<footer>Via {{ child_comment.user }} | {{ child_comment.timestamp|timesince }} ago | {% if request.user == child_comment.user %} <a href="{{ child_comment.get_delete_url }}">Delete</a>{% endif %}</footer>
		</blockquote>
		{% endfor %}
	{% if request.user.is_authenticated %}

	<form method="POST" action=".">{% csrf_token %}
		{{ form|crispy }}
		<input type="hidden" name="parent_id" value="{{ comment.id }}">
		<input type="submit" value="Reply" class="btn btn-default">
	</form>
		</div>
		{% else %}
	<p>You must Login to comment </p>
	{% endif %}

</div>
</div>
{% endblock content %}

project/templates/conform_delete.html
{% extends "base.html" %}

{% load urlify %}
{% load crispy_forms_tags %}

{% block head_title %} {{ instance.title }} | {{ block.supper }} {% endblock head_title %}
{% block content %}

<div class="row">
<div class="col-sm-8 col-sm-offset-4">



	<form method="POST" action=".">{% csrf_token %}
	<h1> Confirm Delete</h1>
		<p>Are you sure you want to delete: "{{ object.content }}"</p>
		<input type="submit" value="Confirm" class="btn btn-warning">
		<a href='{{ object.get_absolute_url }}' class="btn btn-default">Cancle</a>
	</form>
		</div>
		

</div>
</div>
{% endblock content %}

project/templates/form.html
{% extends "base.html" %}
{% load crispy_forms_tags %} 

{% block content %}
<div class="container">
<div class="row">
<div class="col-sm-6 col-sm-offset-3">
<h3>{{ title }}</h3>

<form method="POST" action="" enctype="multipart/form-data">{% csrf_token %}
{{ form|crispy }}
<input type="submit" value="{{ title }}">
</form>
</div>
</div>
</div>
{% endblock %}

project/templates/messages_display.html
{% if messages %}
	<div class="message">
		<ul class="messages">
    	{% for message in messages %}
    	<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    	{% endfor %}
		</ul>
	</div>
{%endif%}

project/templates/post_detail.html
{% extends "base.html" %}

{% load urlify %}
{% load crispy_forms_tags %}

{% block head_title %} {{ instance.title }} | {{ block.supper }} {% endblock head_title %}
{% block content %}

{% block post_detail_link %}
<li><a href='{{ instance.get_absolute_url }}'>{{ instance.title }}</a></li>
{% endblock %}



<div class="row">
<div class="col-sm-8 col-sm-offset-4">
<h1>{{ instance.title }} <small>{% if instance.draft %} <span style="red;"></span>{% endif %}{{ instance.publish}}</small></h1>

<!-- retrive time -->
<p>Read time {% if instance.read_time|time:"i" <= "01" %} 
< 1 minute{% elif instance.read_time|time:"i" %} < 10 minites{% else %} {{ instance.read_time|time:"i" }} Minites {% endif %}</p>

	<img src="{{ instance.image.url }}" class="img-responsive">

 <div class="post-detail-item">
		{{ instance.get_markdown }}
	</div>


<p>Author: {{ instance.user }}<br/>
<p>
<div class="fb-like" data-href="{{ request.build_absolute_uri }}" data-layout="button_count" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div></p>

<p class="lead">Comments</p>
	{% if request.user.is_authenticated %}
<form method="POST" action=".">{% csrf_token %}
	{{ comment_form|crispy }}
	<input type="submit" value="Post comment" class="btn btn-default">
	</form>
	{% else %}
	<p>You must Login to comment </p>
	{% endif %}
	<hr/>
	{% for comment in comments %}

		<blockquote>
			
			<p>{{ comment.content }}</p>

			<footer>Via {{ comment.user }} | {{ comment.timestamp|timesince }} ago | {% if comment.children.count > 0 %} {{ comment.children.count }} Comment{% if comment.children.count > 1 %}s {% endif %}| {% endif %} <a class='comment-reply-btn' href='#'>Reply</a>|<a class='' href='{{ comment.get_absolute_url }}'>Thread</a></footer>

			<!-- Replies -->
	<div class='comment-reply' style="display:none;">
			{% for child_comment in comment.children %}
			<blockquote>

			<p>{{ child_comment.content }}</p>

			<footer>Via {{ child_comment.user }} | {{ child_comment.timestamp|timesince }} ago</footer>
		</blockquote>
		{% endfor %}
	{% if request.user.is_authenticated %}

	<form method="POST" action=".">{% csrf_token %}
		{{ comment_form|crispy }}
		<input type="hidden" name="parent_id" value="{{ comment.id }}">
		<input type="submit" value="Reply" class="btn btn-default">
	</form>
		{% else %}
	<p>You must Login to comment </p>
	{% endif %}
		</div>
			</blockquote>


			<hr/>
			{% endfor %}
</div>
 
<!-- <div class="fb-comments" data-href="{{ request.build_absolute_uri }} data-numposts="5"></div>
 --></p>
</div>
</div>
{% endblock content %}

project/templates/post_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block head_extra %}
{{ form.media }}
{% endblock head_extra %}

{% block content %}
<div class="container">
<div class="row">
<div class="col-sm-6">
<h2>Previews</h2>
<h3 id='preview-title'></h3>

<p id='preview-content'></p>
</div>
<div class="col-sm-6">
<form method="POST" action="" enctype="multipart/form-data">{% csrf_token %}
{{ form|crispy }}
<input type="submit" name="Create Post">
</form>
</div>
</div>
</div>
{% endblock %}

project/templates/post_list.html
{% extends "base.html" %}

	{% block content %}

  <div class="container">
  <div class="row">
		<h1>{{ title }}</h1>

  <div class="input-group">
    <form method='GET' action="">
      <input class="form-control" type='text' name='q' placeholder="Search Posts" value="{{ request.GET.q }}" />
      <span class="input-group-btn">
        <!-- <input class="btn btn-defualt" type="submit"  value='search' /> -->
        <button class="btn btn-defualt" type="submit">Search <i class="fas fa-search"></i></button>
      </span>
    </form>

  </div>
    {% for obj in query_list %}

    <div class="card">
      		<div class="thumbnail">

      {% if obj.image %}
      		<img src="{{ obj.image.url }}" class="img-responsive">
      {% endif %}
			<div class="caption post-detail-item">
      {% if obj.droft %}<h3>Staff Only: Draft</h3> {% endif %} {% if obj.publish > today %}<h3>Future Post</h3>{% endif %}
		<h3><a href='{{ obj.get_obsolute_url }}'>{{ obj.title }}</a>

    <small>{{ obj.publish }}</small></h3>
    <p>Author: {{ obj.user }}
		<p class="">{{ obj.get_markdown|truncatechars_html:50 }}</p>
		<p><a href="{{ obj.get_obsolute_url }} " class="btn btn-primary" role="button">Views</a></p>
	</div>
</div>
</div>
</div>
<!-- {% cycle "" "<div class='col-sm-12'><hr/></div></div><div class='row'>" %}
 -->
{% endfor %}

<div class="pagination">
    <span class="step-links">
        {% if query_list.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ query_list.previous_page_number }} 
            {% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ query_list.number }} of {{ obj.paginator.num_pages }}
        </span>

        {% if query_list.has_next %}
            <a href="?page={{ query_list.next_page_number }}
            {% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">next</a>
        {% endif %}
    </span>
</div>


</div>
{% endblock content %}